config/routes.rb
Rails.application.routes.draw do
  root to: 'people#index'
  resources :people, { only: [:index, :show], param: :identifier }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  self.table_name = "people"

  # relationships
  belongs_to :father, class_name: "Person", optional: true
  belongs_to :mother, class_name: "Person", optional: true

  # attributes
  validates :name, presence: true
  validates :identifier, presence: true

  #methods
  def children
    self.class.where("father_id = ? OR mother_id = ?", self.id, self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
    render :index
  end

  def show
    @person = Person.find_by(identifier: params.fetch(:identifier))
    render :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mawie</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/index.html.erb
<h1>The Gatopan Family (circa 103 b.c.)</h1>
<table>
  <thead>
    <% Person.column_names.each do |header| %>
      <th><%= header %></th>
    <% end %>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.id %></td>
        <td><%= person.name %></td>
        <td><%= link_to person.identifier, person_path(person.identifier) %></td>
        <td>
          <% unless person.father_id == nil %>
            <% father_identifier = Person.find_by!(id: person.father_id).identifier %>
            <%= link_to person.father_id, person_path(father_identifier) %>
          <% end %>
        </td>
        <td>
          <% unless person.mother_id == nil %>
            <% mother_identifier = Person.find_by!(id: person.mother_id).identifier %>
            <%= link_to person.mother_id, person_path(mother_identifier) %>
          <% end %>
        </td>
        <td><%= person.created_at %></td>
        <td><%= person.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/people/index2.html.erb
<h1>The Gatopan Family (circa 103 b.c.)</h1>
<table>
  <thead>
    <% Person.column_names.each do |header| %>
      <th><%= header %></th>
    <% end %>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.id %></td>
        <td><%= person.name %></td>
        <td><%= link_to person.identifier, person_path(person.identifier) %></td>
        <td>
          <% if person.father %>
            <%= link_to person.father.name, person_path(person.father.identifier) %>
          <% end %>
        </td>
        <td>
          <% if person.mother %>
            <%= link_to person.mother.name, person_path(person.mother.identifier) %>
          <% end %>
        </td>
        <td><%= person.created_at.to_formatted_s(:long) %></td>
        <td><%= person.updated_at.to_formatted_s(:long) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/people/show.html.erb
<h1><%= @person.name %></h1>
<table>
  <thead>
    <% Person.column_names.each do |header| %>
      <th><%= header %></th>
    <% end %>
  </thead>
  <tbody>
    <tr>
      <td><%= @person.id %></td>
      <td><%= @person.name %></td>
      <td><%= @person.identifier %></td>
      <td>
        <% if @person.father %>
          <%= link_to person.father.name, person_path(person.father.identifier) %>
        <% end %>
      </td>
      <td>
        <% if @person.mother %>
          <%= link_to person.mother.name, person_path(person.mother.identifier) %>
        <% end %>
      </td>
      <td><%= @person.created_at %></td>
      <td><%= @person.updated_at %></td>
    </tr>
  </tbody>
</table>